### ISSUE TITLE
"More Workstations" mod gives "Exception: Block with name 'stone' not found!

### ISSUE THREAD

**Issue by sihorton** [7D2DSDX/Mods#2]
I am using SDX Mod Helper 1.1.0.14, SDX Launcher 0.7.1 and Alpha6.4 (b8). If I select "More Workstations" as the only mod, or as one of several mods then it builds fine and 7 days runs but when starting a new game or continuing an existing game it crashes at Initializing world.

I cannot see anywhere in the mod where it is using the text stone anywhere so maybe it is inside one of the resources?

![capture2](https://user-images.githubusercontent.com/1965231/32290094-44414fbc-bf39-11e7-9f67-791122e3e984.png)

**Comment by SphereII** [comment]
Strange. As you said, there is no stone blocks. It sounds like a corrupted blocks.xml.

Can you post the full output_log.txt?

**Comment by sihorton** [comment]
Here is the output_log.txt, I started a new game with only the "More Workstations" mod selected.

[output_log.txt](https://github.com/7D2DSDX/Mods/files/1435348/output_log.txt)

**Comment by sihorton** [comment]
Just for more information, if I uncheck the "More Workstations" mod then everything works ok, I can run several SDX mods with the same settings and game directory and everything, so it is something connected to that single mod somehow.

**Comment by sihorton** [comment]
Your comment gave me an idea of what it could be:--

Looking in the game directory (Data/Config/blocks.xml) there is actually:
`<block id="1" name="stone">` however if I scroll to the bottom of the file then I see what the problem is:

`<block id="1" name="NewWorkBench">`
	`<block id="1" name="Anvil">`
	`<block id="1" name="TanningRack">`
	`<block id="1" name="GrindingWheel">`
	`<block id="1" name="CampFire">`
	`<block id="1" name="ResearchDesk">`
	`<block id="1" name="BigForge">`

The workstations it is adding in are all being given a block id of 1 and that is then replacing the stone block. Github did not allow me to upload the .xml so it is renamed to .xml.txt:

[blocks.xml.txt](https://github.com/7D2DSDX/Mods/files/1435362/blocks.xml.txt)

**Comment by sihorton** [comment]
If I replace the id="1" with id="" in the mod then the new workstations get a new id correctly. I can submit a pull request with the fix.

**Comment by sihorton** [comment]
Issue is now fixed with the latest commit.
